spring:
  application:
   name: TestApp
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/test_app?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
server:
  port: 8086

jwt:
  expiration-in-ms: 86400000
  key: ${JWT_KEY:PT09PT09PT09PT09PT09PWtleV9leGFtcGxlX3N2X2t1bGljaF90ZXN0X2RhdGE9PT09PT09PT09PT09PT09PQ==}
