spring:
  application:
   name: TestApp
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/test_app?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
server:
  port: 8086

